apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cricket-feedback
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ocir-creds
      containers:
        - name: backend
          image: phx.ocir.io/axkw6whnjncs/cricket-feedback-backend:v15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "5001"
            - name: MONGODB_URI
              value: "mongodb://admin:password123@mongodb-service:27017/cricket-feedback?authSource=admin"
            - name: WHATSAPP_PHONE_NUMBER_ID
              value: "902819506256035"
            - name: WHATSAPP_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: whatsapp-credentials
                  key: WHATSAPP_ACCESS_TOKEN
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cricket-secrets
                  key: jwt-secret
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: cricket-secrets
                  key: google-client-id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cricket-secrets
                  key: google-client-secret
            - name: SUPER_ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: cricket-secrets
                  key: super-admin-key
            # AI Service URL for payment screenshot parsing
            - name: AI_SERVICE_URL
              value: "http://ai-service:8000"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: cricket-feedback
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP