apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: cricket-feedback
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ocir-creds
      containers:
        - name: frontend
          image: phx.ocir.io/axkw6whnjncs/cricket-feedback-frontend:v7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "https://129.153.86.8.sslip.io/api"
            - name: REACT_APP_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: cricket-secrets
                  key: google-client-id
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: cricket-feedback
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP