# GCP App Engine Configuration
runtime: custom
env: flex

# Instance configuration
instance_class: F2
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

# Auto-scaling
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cpu_utilization:
    target_utilization: 0.75

# Health check
health_check:
  enable_health_check: True
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

# Network configuration
network:
  forwarded_ports:
    - 80:80
    - 443:443

# Environment variables (set in GCP Console or via gcloud)
env_variables:
  NODE_ENV: production
  PORT: 5001

# Readiness check
readiness_check:
  path: "/api/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

# Liveness check
liveness_check:
  path: "/api/health"
  initial_delay_sec: 300
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
